@startuml full_act
<style file=plantStyle.css>
title "Wordle-Time vollständiger Workflow"

|wordle-time Frontend|
start
:Spiel initialisieren;
repeat
    :Rateversuch eingeben;
    :Rateversuch (ggf. mit gameID Cookie) senden;
    |wordle-time Backend|
    :Rateversuch empfangen;
    if(Wortlänge prüfen) then (Wortlänge != 5)
        :Sende BadRequest;
    elseif (Prüfe gameID) then (gameID != null && gameID != currentGameID)
        if(Prüfe gestrige gameID) then (gameID = yesterdayGameID)
            :Sende NotFound mit oldWord;
        else (gameID != yesterdayGameID)
            :Sende NotFound;
        endif
    else (Wortlänge und gameID valide)
        :Validiere word;
        :Sende OK mit GuessResult Body und gameID set-cookie Header;
    endif
    |wordle-time Frontend|
    :Antwort empfangen;
    switch (Antwort)
    case (BadRequest)
        :Zeige "Geratenes Wort hat nicht 5 Buchstaben";
    case (NotFound)
        :Lösche gameID Cookie;
        if(NotFound enthält oldWord) then (Ja)
            :Zeige "Altes Wort $oldWord";
        endif
        :Zeige "Zu ratendes Wort hat sich geändert. Starte neu"
        :Re-Initialisiere neues Spiel;
        stop
    case (OK)
        :gameID von set-cookie Header in Browser CookieJar speichern;
        note right
            Geschieht automatisch?
        end note
        :Färbe Buchstaben entsprechend ein;
        if(Alle Buchstaben "CorrectSpot") then (Ja)
            :Zeige "Wort erfolgreich geraten";
            stop
        else (Nein)
        endif
        :RateVersuche++;
    endswitch
    backward:Biete neuen Rate-Versuch;
repeat while (Rateversuche < 6) is (Ja)
-> Nein;
:Zeige "Verloren. Zu viele Rateversuche";
stop
@enduml