openapi: "3.0.3"
info:
  title: "wordle_time API"
  description: "wordle_time API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
paths:
  /api/guess:
    get:
      description: "Guess the current wordl of the day."
      parameters:
        - name: "gameID"
          in: "cookie"
          required: false
          schema:
            type: "string"
        - name: "word"
          in: "query"
          required: true
          schema:
            type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/GuessLengthError"
              examples:
                Example#1:
                  description: "Example for GuessLengthError"
                  value:
                    word: "app"
        "403":
          description: "Not Found"
          content:
            'application/json':
              schema:
                oneOf:
                  - $ref: "#/components/schemas/OldGameIDError"
                  - $ref: "#/components/schemas/WrongGameIDError"
              examples:
                Example#1:
                  description: "Example for WrongGameIDError"
                  value:
                    gameID: "aaaaaaaaaaaaaaa"
                    word: "applu"
        "200":
          description: "OK"
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/GuessResult"
components:
  schemas:
    OldGameIDError:
      type: "object"
      properties:
        oldWord:
          type: "string"
        message:
          type: "string"
    WrongGameIDError:
      type: "object"
      properties:
        message:
          type: "string"
    GuessLengthError:
      type: "object"
      properties:
        guessedWord:
          type: "string"
        message:
          type: "string"
    GuessResult:
      type: "object"
      properties:
        letterStates:
          type: "array"
          items:
            type: "string"
            enum:
              - "CorrectSpot"
              - "WrongSpot"
              - "WrongLetter"
