@startuml F002_act
<style file=plantStyle.css>
title "Feedback-Mechanismus"

|Backend|
|Frontend|
|Spieler|

|Backend|
start
:Ergebnis der Rateversuch-Validierung senden;
|Frontend|
:Ergebnis der Rateversuch-Validierung empfangen;
:Buchstaben-Rahmen Farben entsprechend validität zuweisen;
:Buchstaben-Rahmen anzeigen;
|Spieler|
:Buchstaben-Rahmen ansehen und Validität verstehen;
note right
    correct_letter: Korrekter Buchstabe wurde an richtiger Stelle eingegeben
    wrong_spot: Korrekter Buchstabe wurde an falscher Stelle eingegeben
    wrong_letter: Falscher Buchstabe wurde eingegeben
end note
end

@enduml